### ISSUE TITLE
Bug report: Ошибка при запуске Chrome Standalone в Windows 8.1

### ISSUE THREAD

**Issue by reponame** [reponame/chromestandalone#3]
При попытке запуска Chrome Standalone на Windows 8.1 происходит ошибка "File not found". Версия Chrome Standalone - 1.0.1. Версия Windows 8.1 - сборка 9600. Приложить скриншот ошибки и логи.

**Comment by DedInc** [comment]
Было бы удобно добавить опцию, которая позволит включать автоматический запуск Chrome Standalone при старте системы. Это позволит пользователям быстрее начинать работу с приложением.

**Comment by reponame** [comment]
> Было бы удобно добавить опцию, которая позволит включать автоматический запуск Chrome Standalone при старте системы. Это позволит пользователям быстрее начинать работу с приложением.

Fixed
